---CREATE VIEW MARK REPORT FOR DBI202
CREATE VIEW MARK_REPORT_DBI202 AS 
     SELECT StudentID,Category,Grade FROM GRADING
	 WHERE CourseID='DBI202'

---CREATE VIEW MARK REPORT FRO CSD201
CREATE VIEW MARK_REPORT_CSD201 AS 
     SELECT StudentID,Category,Grade FROM GRADING
	 WHERE CourseID='CSD201'

---SELECT
SELECT * FROM MARK_REPORT_DBI202
SELECT * FROM MARK_REPORT_CSD201

/*DROP VIEW MARK_REPORT_DBI202
DROP VIEW MARK_REPORT_CSD201*/